FROM amazonlinux:2 as installer
RUN yum update -y \
  && yum install -y unzip curl tar gzip \
  && curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscli-exe-linux-x86_64.zip \
  && unzip awscli-exe-linux-x86_64.zip \
  # The --bin-dir is specified so that we can copy the
  # entire bin directory from the installer stage into
  # into /usr/local/bin of the final stage without
  # accidentally copying over any other executables that
  # may be present in /usr/local/bin of the installer stage.
  && ./aws/install --bin-dir /aws-cli-bin/ 

# ADD eksctl
RUN curl --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp 

FROM amazonlinux:2
ENV KUBE_LATEST_VERSION="v1.21.12"
COPY --from=installer /usr/local/aws-cli/ /usr/local/aws-cli/
COPY --from=installer /aws-cli-bin/ /usr/local/bin/
COPY --from=installer /tmp/eksctl /usr/local/bin/

RUN yum update -y \
  && yum install -y less vim curl python3 pip3 \
  && yum clean all
RUN export ARCH="$(uname -m)" && if [[ ${ARCH} == "x86_64" ]]; then export ARCH="amd64"; elif [[ ${ARCH} == "aarch64" ]]; then export ARCH="arm64"; fi && curl -L https://dl.k8s.io/release/${KUBE_LATEST_VERSION}/bin/linux/${ARCH}/kubectl -o /usr/local/bin/kubectl \
 && chmod +x /usr/local/bin/kubectl
RUN pip3 install kubernetes boto3

# IAM authenticator is required so that kukbectl can see what you are allowed by IAM rules to deal with kubernetes
RUN curl -o /usr/bin/aws-iam-authenticator https://s3.us-west-2.amazonaws.com/amazon-eks/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator
RUN chmod +x /usr/bin/aws-iam-authenticator


ENTRYPOINT ["sh", "-c", "while true; do sleep 3600; done"]

# Using this file builds a container that will allow you to run kubectl of your favorite version, just change the first line to represent the version you want. 

# MIT License - Use at your own risk

# docker build -t charmingsteve/kubectleks:1.21_v_02 -f Dockerfile-kubectl-awscli .

# docker run  d --rm  -v /home/steve/.kube-eks:/root/.kube -v /home/steve/.aws:/root/.aws  charmingsteve/kubectleks:1.21_v_02 -c "aws eks update-kubeconfig --region us-east-2 --name eks-autoscaling"

# docker run  -d  --rm  -v /home/steve/.kube-eks:/root/.kube -v /home/steve/.aws:/root/.aws  charmingsteve/kubectleks:1.21_v_02 -c "kubectl get svc"
