FROM amazonlinux:2 as installer
RUN yum update -y \
  && yum install -y unzip curl tar gzip \
  && curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscli-exe-linux-x86_64.zip \
  && unzip awscli-exe-linux-x86_64.zip \
  # The --bin-dir is specified so that we can copy the
  # entire bin directory from the installer stage into
  # into /usr/local/bin of the final stage without
  # accidentally copying over any other executables that
  # may be present in /usr/local/bin of the installer stage.
  && ./aws/install --bin-dir /aws-cli-bin/ 

# ADD eksctl
RUN curl --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp 

FROM amazonlinux:2
ENV KUBE_LATEST_VERSION="v1.21.12"
COPY --from=installer /usr/local/aws-cli/ /usr/local/aws-cli/
COPY --from=installer /aws-cli-bin/ /usr/local/bin/
COPY --from=installer /tmp/eksctl /usr/local/bin/

RUN yum update -y \
  && yum install -y less vim curl \
  && yum clean all
RUN export ARCH="$(uname -m)" && if [[ ${ARCH} == "x86_64" ]]; then export ARCH="amd64"; elif [[ ${ARCH} == "aarch64" ]]; then export ARCH="arm64"; fi && curl -L https://dl.k8s.io/release/${KUBE_LATEST_VERSION}/bin/linux/${ARCH}/kubectl -o /usr/local/bin/kubectl \
 && chmod +x /usr/local/bin/kubectl

# IAM authenticator is required so that kukbectl can see what you are allowed by IAM rules to deal with kubernetes
RUN curl -o /usr/bin/aws-iam-authenticator https://s3.us-west-2.amazonaws.com/amazon-eks/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator
RUN chmod +x /usr/bin/aws-iam-authenticator

ENTRYPOINT ["/bin/sh"]



#!!! ADD EKSCTL 

# Using this file builds a container that will allow you to run kubectl of your favorite version, just change the first line to represent the version you want. Take the tag from Docker Hub  bitnami/kubectl.

# MIT License - Use at your own risk

# docker build -t charmingsteve/kubectleks:1.21_v_02 -f Dockerfile-kubectl-awscli .

# docker run -it  --rm --name kubectl -v /home/steve/.kube-souel/config:/root/.kube/config -t /home/steve/.aws:/root/.aws 



# FROM alpine 



# Based upon https://github.com/aws/aws-cli/blob/2.0.10/docker/Dockerfile



# https://www.jeffgeerling.com/blog/2018/install-kubectl-your-docker-image-easy-way
# https://hub.docker.com/r/lachlanevenson/k8s-kubectl
# docker run -it  --rm -u root  --name kubectl -v /home/steve/.kube-souel/config:/.kube/config --entrypoint bash  bitnami/kubectl:1.21.14-debian-11-r1

# root@1905071de536:/# echo $PATH
# /opt/bitnami/kubectl/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin


#RUN ln -s /usr/local/aws-cli/v2/current/bin/aws /usr/local/bin/aws && \
#   ln -s /usr/local/aws-cli/v2/current/bin/aws_completer /usr/local/bin/aws_completer


#
## Install AWS cli and iam authenticator
#RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
#RUN unzip awscliv2.zip
#RUN ./aws/install -i /usr/local/aws-cli -b /usr/local/bin



#WORKDIR /root
#ENTRYPOINT ["kubectl"]
#CMD ["help"]
